baseURL = "https://blog.thevinesh.com"
title = "Vinesh's Blog"
theme = "hugo-notepadium"
copyright = "© Vinesh Raju."

summaryLength = 25 
languageCode = "en-uk"
hasCJKLanguage = false

enableGitInfo = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = "XXX"

googleAnalytics = "UA-142502015-1"

[markup.highlight]
  codeFences = true
  noClasses = false

[markup.goldmark.renderer]
  unsafe = false  # enable raw HTML in Markdown

[params]
  style = "auto"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
  dateFormat = "Jan 2, 2006"
  logo = "" #logo here
  slogan = ""
  license = ""  # CC License
  fullRss = true # Puts entire HTML post into rss 'description' tag. If unset, default is false.

[params.assets]
  css = ["css/color.css","css/font.css","css/accessibility.css","css/tooltip.css"]
  js = ["js/copy.js"]

[params.comments]
  enable = false  # En/Disable comments globally, default: false. You can always enable comments on per page.

[params.math]
  enable = false  # optional: true, false. Enable globally, default: false. You can always enable math on per page.
  use = "katex"  # option: "katex", "mathjax". default: "katex"

[params.syntax]
  use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
  theme = "xcode"
  darkTheme = "xcode-dark"  # apply this theme in dark mode

[params.share]
  enable = true
  hookText = '''
  Liked what you just read?  
  Spread the word!
  '''
  whatsapp = "https://api.whatsapp.com/send?text="
  twitter = "https://twitter.com/intent/tweet?url="
  email = "mailto:?subject=Check out this link&body="
  # addThisId = "ra-6056429fe44ee3ed"

[params.nav]
  showCategories = false
  showTags = false

[params.profile]
  enable = true
  avatar = "imgs/author.png"
  name = "Vinesh Raju"
  articleFooter = "I'd love to talk. Feel free to reach me at 👇"
  handle = "theVinesh"
  email = "hi@thevinesh.com"

[params.font]
  googlefont = "Oxygen Mono"